

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:6006/theday?characterEncoding=UTF-8
    username: root
    password: rootroot
    
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  port: 80
  
file:
  upload-path :  C:\spring_project\theday\workspace\images/


  